application: lesson3-is206
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  
- url: /static
  static_dir: static

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
